#!/usr/bin/env bash
CONFIG="$HOME/.config/hypr/alacritty/alacritty.toml"

if [ "$1" == "-f" ]; then
	shift
	alacritty --class 'alacritty-float,alacritty-float' --config-file "$CONFIG" $@
elif [ "$1" == "-F" ]; then
	shift
	alacritty --class 'alacritty-fullscreen,alacritty-fullscreen' --config-file "$CONFIG" \
			  -o window.startup_mode="'Fullscreen'" \
			  window.padding.x=30 window.padding.y=30 \
			  font.size=14 $@
else
	alacritty --config-file "$CONFIG" $@
fi
