#!/usr/bin/env bash
# Copyright (C) 2025 choozn
# Backlight script

get_backlight_percentage() {
	LIGHT=$(printf "%.0f\n" `light -G`)
	echo "${LIGHT}%"
}

show_notification() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify-backlight -u low "Brightness : $(get_backlight_percentage)"
}

if [[ "$1" == "--inc" ]]; then
	light -A 5 && show_notification
elif [[ "$1" == "--dec" ]]; then
	light -U 5 && show_notification
else
	get_backlight_percentage
fi
