#!/usr/bin/env bash

_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Polkit agent
if [[ ! `pidof polkit-mate-authentication-agent-1` ]]; then
	/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
fi

# Set wallpaper
~/.config/hypr/scripts/wallpaper &

# Apply theme
~/.config/hypr/scripts/gtkthemes &

# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Lauch waybar
~/.config/hypr/scripts/waybar &

# Start mpd
exec mpd &
