#!/usr/bin/env bash

_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Set wallpaper
~/.config/hypr/scripts/wallpaper &

# Apply themes
~/.config/hypr/scripts/gtkthemes &

# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Lauch waybar
~/.config/hypr/scripts/waybar &

# Start network manager applet
nm-applet --indicator &

# Start mpd
exec mpd &
