#!/usr/bin/env bash
# Copyright (C) 2025 choozn
# System update script

# Start system update
echo "[!] Starting a system update."

if command -v topgrade &> /dev/null; then
  topgrade
elif command -v yay &> /dev/null; then
  yay
else
  sudo pacman -Syu
fi; 

exec zsh
